export default function RebalancePlan() {
  return (
    <>
      <p>
        The rebalance plan is the second panel in the dashboard. It turns the
        gap between your current allocation and your target allocation into a
        concrete, ordered list of trades — and writes a one-sentence
        explanation that reads like a memo, not a log file.
      </p>

      <h2>What the panel shows</h2>

      <ul>
        <li>
          <strong>Orders</strong> — a ranked list of buys and sells, sized in
          both token units and USD. Sells are listed first so proceeds are
          available for the buys that follow.
        </li>
        <li>
          <strong>Explanation</strong> — a plain-English paragraph describing
          which assets moved, by how much, and what the trades are intended
          to do.
        </li>
        <li>
          <strong>Status pill</strong> — either <code>On target</code>,{" "}
          <code>Mild drift</code>, or <code>Rebalance recommended</code>,
          matching the dashboard header.
        </li>
      </ul>

      <h2>How order sizes are calculated</h2>

      <p>
        The math is intentionally simple — simple enough that you can replay
        it on a napkin.
      </p>

      <ol>
        <li>
          Compute <strong>total portfolio value</strong> in USD.
        </li>
        <li>
          For each asset, compute the <strong>target value</strong> — target
          weight × total portfolio value.
        </li>
        <li>
          Subtract current value from target value. The result is the{" "}
          <strong>USD delta</strong>: positive means buy, negative means
          sell.
        </li>
        <li>
          Convert the USD delta to a token amount at the live price.
        </li>
      </ol>

      <p>
        Dust orders under a floor of $1 are dropped — they would move the
        index less than a rounding error and add gas cost.
      </p>

      <h2>What the explanation means</h2>

      <p>
        The one-sentence summary is generated by the rebalance engine itself,
        not by an external language model. It names the asset with the
        largest drift, states the direction, and explains the corrective
        trade.
      </p>

      <blockquote>
        ETH drifted 12% above target. Selling 0.4 ETH restores your index.
      </blockquote>

      <p>
        If multiple assets drifted, the explanation leads with the largest
        mover and groups the rest into a second clause. The goal is one
        sentence you can screenshot and paste into a trading journal — not a
        paragraph you have to read twice.
      </p>

      <h2>Acting on the plan</h2>

      <p>
        The plan is advisory. Nothing executes until you choose to execute.
        When SoDEX integration is enabled the plan hands off directly; until
        then, the <strong>Execute on SoDEX</strong> button opens SoDEX in a
        new tab so you can place the trades manually. See{" "}
        <em>Executing on SoDEX</em> for the current flow.
      </p>
    </>
  );
}
