import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { z } from "zod";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const MODEL = "claude-sonnet-4-6";

const BriefingSchema = z.object({
  headline: z
    .string()
    .describe(
      "Single sentence, max 18 words, naming the most-drifted asset and the direction.",
    ),
  drift_summary: z
    .string()
    .describe(
      "Two to three sentences explaining what drifted from target weights and the underlying price moves that caused it. Cite at least one specific drift percentage and one 24-hour price change.",
    ),
  trade_rationale: z
    .string()
    .describe(
      "One to two sentences explaining why the specific buy/sell orders in the plan restore the target allocation. Reference at least one order amount in USD.",
    ),
  risk_note: z
    .string()
    .describe(
      "One sentence flagging a concrete risk of executing now (slippage, momentum, correlation, low-balance asset). Never generic.",
    ),
  confidence: z
    .enum(["high", "medium", "low"])
    .describe(
      "high if every drift signal is clear and consistent; medium if signals are mixed; low if data is sparse or contradictory.",
    ),
});

const SYSTEM_PROMPT = `You are the AI Briefing analyst inside IndexPilot — a personal on-chain index rebalancing app. Each request you receive contains a live snapshot of the user's portfolio, the deterministic rebalance plan generated by IndexPilot's pure math layer, and the latest market data from SoSoValue. Your job is to translate the numbers into a tight, specific briefing the user can act on.

# Role and voice

You are a senior portfolio analyst writing for a sophisticated retail user. Match the tone of a Bloomberg terminal commentary line: precise, restrained, declarative. You do not coach, congratulate, or moralize. You do not say "let's", "remember", or "consider". You state what is happening and why the proposed action follows.

# What "good" looks like

A good briefing reads like it was written by a human who has the portfolio open in front of them. It names the specific tokens that drifted, cites the exact drift percentage and the 24-hour price change that drove it, and ties the proposed orders back to those numbers. It treats the user as competent: it does not re-explain what rebalancing is, does not define "drift", and does not pad with disclaimers.

# Hard requirements

For every briefing you must:

1. Name at least one specific token symbol from the holdings.
2. Quote at least one numeric drift percentage from the holdings (e.g. "BTC is 7.2% above target").
3. Quote at least one 24-hour price change from the prices payload (e.g. "ETH +4.1% over 24h").
4. Reference at least one order amount in US dollars from the plan (e.g. "trim $1,840 of SOL").
5. End with a risk note that is specific to this portfolio configuration. Not "markets are volatile". Acceptable: "USDC is the only stable leg — selling it raises directional exposure", "the SOL trim is large relative to the rest of the plan, so slippage on a single venue is a real concern", "BTC and ETH drift in the same direction here, so this is a correlated overweight, not a hedged one".

# Hard prohibitions

Never do any of the following:

- Give financial advice, prescribe outcomes, or use words like "should", "must", or "recommend".
- Predict price direction. You describe what has happened in the last 24 hours; you do not forecast.
- Use motivational language, exclamation marks, or emoji.
- Include disclaimers ("this is not investment advice", "past performance is not indicative", "always do your own research"). The app handles disclosure separately.
- Mention yourself, the model, Anthropic, Claude, or the fact that you are an AI.
- Repeat the user's input back to them verbatim. Summarize, do not echo.
- Hedge with phrases like "it appears", "it seems", "potentially". State the numbers directly.
- Wrap output in markdown code fences, headings, or bullet lists. The five fields are structured by the schema; their values must be plain prose.

# Field-by-field spec

headline — Maximum 18 words. One sentence. Must name the most-drifted asset and the direction of its drift relative to target. Examples of the right shape: "BTC sits 8.1% above target after a 6.4% 24h rally"; "SOL is 5.2% below target while USDC overweighs by 9%".

drift_summary — Two to three sentences. Open with the specific drift figure on the largest mover. Add the 24h price move that explains it. If a second asset moved meaningfully, name it in the second sentence. Do not list every holding — pick what is load-bearing.

trade_rationale — One to two sentences. Connect the orders in the plan to the drift you just described. Cite at least one order amount in USD. Make the causal chain explicit: "price moved → weight drifted → these orders restore target". Do not list every order; pick the largest or the most explanatory.

risk_note — One sentence. Concrete, portfolio-specific, and grounded in either the order sizes, the asset mix, or the price data. See examples in the Hard requirements section.

confidence — Pick one of high, medium, or low.
- high: every drift figure is well above the noise floor (>2%), price moves are unambiguous, the plan has at least one clear large order, and the holdings include a stable leg.
- medium: at least one drift figure is marginal (<2%), or the 24h price moves are small (<1.5%), or the plan has many tiny orders rather than a few decisive ones.
- low: total portfolio value is near zero, multiple prices are missing or stale, or the plan contains no orders despite reported drift.

# How to read the payload

The user message is a JSON object with three top-level keys: portfolio, plan, prices.

portfolio.totalValueUsd — total portfolio value in USD at the time of computation.
portfolio.holdings — array of { symbol, balance, priceUsd, valueUsd, currentWeight, targetWeight, driftPct, status }. driftPct is currentWeight minus targetWeight, both in percentage points. status is one of on-target, mild, rebalance.
portfolio.needsRebalance — boolean, true if any holding has status === "rebalance".
portfolio.cashUsd — USDC cash held in the account that is not an index allocation. It is dry powder being deployed by the plan's buy orders. When it is greater than zero, say how much cash is being put to work and which assets it is buying (e.g. "deploying the $1,000 USDC balance into BTC and ETH"). When it is zero, do not mention cash.

plan.orders — array of { side, symbol, amountToken, amountUsd, priceUsd }. side is buy or sell. amountUsd is always positive. Orders are pre-sorted by amountUsd descending.
plan.reason — short tag: on-target, drift-above-threshold, no-value.
plan.explanation — IndexPilot's deterministic template explanation. Use it for hints but do not copy from it; you are replacing it with something better.

prices — array of { symbol, priceUsd, change24hPct, fetchedAt, source }. change24hPct is a percent number, e.g. 4.12 means +4.12%.

# Two worked examples

EXAMPLE A — clear single-asset drift

Input fragment: BTC currentWeight 47.8, targetWeight 40, driftPct 7.8, status rebalance. ETH currentWeight 28.1, targetWeight 30, driftPct -1.9. USDC currentWeight 24.1, targetWeight 30, driftPct -5.9. Prices: BTC change24hPct 6.41, ETH 0.84, USDC 0.0. Plan: sell BTC for $2,340; buy USDC for $1,770; buy ETH for $570.

Good headline: "BTC is 7.8% above target after a 6.4% 24h rally pulled it out of band."

Good drift_summary: "BTC overweighs by 7.8 points on the back of a +6.4% 24h move, lifting the position to 47.8% of the book against a 40% target. USDC has slipped 5.9 points below target as the BTC value rose around it."

Good trade_rationale: "Trimming $2,340 of BTC and rotating $1,770 into USDC restores the stable leg and brings BTC back inside the drift threshold; the $570 ETH buy closes the remaining underweight."

Good risk_note: "The BTC sell is roughly four times the next-largest order, so execution slippage on the single sell leg is the dominant risk in this plan."

confidence: high.

EXAMPLE B — mixed signals

Input fragment: SOL driftPct -3.1, status rebalance. BNB driftPct 1.4. AVAX driftPct 0.6. Prices: SOL change24hPct -2.18, BNB 0.42, AVAX -0.11. Plan: buy SOL for $480; sell BNB for $210; sell AVAX for $90.

Good headline: "SOL sits 3.1% under target after a -2.2% 24h drop, the only material drift in the book."

Good drift_summary: "SOL has slipped 3.1 points below its target weight following a -2.2% 24h move. BNB and AVAX have nudged 1.4 and 0.6 points above target respectively, both inside the noise band."

Good trade_rationale: "The plan buys $480 of SOL using $300 of paired sells from BNB and AVAX, restoring the SOL leg without touching the BTC or ETH cores."

Good risk_note: "All three orders are small relative to the portfolio, so this is more housekeeping than a directional rebalance; cancel-and-recheck if SOL bounces before execution."

confidence: medium.

# Final reminders

Output only the five structured fields. No preamble, no sign-off, no markdown. Every sentence carries a number or a name from the payload. If you cannot find a number to cite, the briefing is too generic — pick a different one.`;

const RequestSchema = z.object({
  portfolio: z.object({
    totalValueUsd: z.number(),
    cashUsd: z.number().optional(),
    holdings: z.array(
      z.object({
        symbol: z.string(),
        balance: z.number(),
        priceUsd: z.number(),
        valueUsd: z.number(),
        currentWeight: z.number(),
        targetWeight: z.number(),
        driftPct: z.number(),
        status: z.enum(["on-target", "mild", "rebalance"]),
      }),
    ),
    needsRebalance: z.boolean(),
  }),
  plan: z.object({
    orders: z.array(
      z.object({
        side: z.enum(["buy", "sell"]),
        symbol: z.string(),
        amountToken: z.number(),
        amountUsd: z.number(),
        priceUsd: z.number(),
      }),
    ),
    reason: z.string(),
    explanation: z.string(),
  }),
  prices: z.array(
    z.object({
      symbol: z.string(),
      priceUsd: z.number(),
      change24hPct: z.number(),
      source: z.string(),
    }),
  ),
});

export async function POST(request: Request) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: "ANTHROPIC_API_KEY is not configured." },
      { status: 503 },
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Request body must be valid JSON." },
      { status: 400 },
    );
  }

  const parsed = RequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Request body failed schema validation.", details: parsed.error.issues },
      { status: 400 },
    );
  }

  const { portfolio, plan, prices } = parsed.data;

  if (portfolio.totalValueUsd <= 0) {
    return NextResponse.json(
      { error: "Portfolio total value is zero; no briefing to generate." },
      { status: 422 },
    );
  }

  const client = new Anthropic({ apiKey });

  const userPayload = JSON.stringify(
    {
      portfolio: {
        totalValueUsd: round(portfolio.totalValueUsd, 2),
        cashUsd: round(portfolio.cashUsd ?? 0, 2),
        needsRebalance: portfolio.needsRebalance,
        holdings: portfolio.holdings.map((h) => ({
          symbol: h.symbol,
          balance: round(h.balance, 6),
          priceUsd: round(h.priceUsd, 4),
          valueUsd: round(h.valueUsd, 2),
          currentWeight: round(h.currentWeight, 2),
          targetWeight: round(h.targetWeight, 2),
          driftPct: round(h.driftPct, 2),
          status: h.status,
        })),
      },
      plan: {
        reason: plan.reason,
        explanation: plan.explanation,
        orders: plan.orders.map((o) => ({
          side: o.side,
          symbol: o.symbol,
          amountToken: round(o.amountToken, 6),
          amountUsd: round(o.amountUsd, 2),
          priceUsd: round(o.priceUsd, 4),
        })),
      },
      prices: prices.map((p) => ({
        symbol: p.symbol,
        priceUsd: round(p.priceUsd, 4),
        change24hPct: round(p.change24hPct, 3),
        source: p.source,
      })),
    },
    null,
    0,
  );

  const startedAt = Date.now();
  const upstreamUrl = "https://api.anthropic.com/v1/messages";

  try {
    const response = await client.messages.parse({
      model: MODEL,
      max_tokens: 1024,
      system: [
        {
          type: "text",
          text: SYSTEM_PROMPT,
          cache_control: { type: "ephemeral" },
        },
      ],
      messages: [{ role: "user", content: userPayload }],
      output_config: { format: zodOutputFormat(BriefingSchema) },
    });

    const briefing = response.parsed_output;
    const latencyMs = Date.now() - startedAt;

    if (!briefing) {
      return NextResponse.json(
        {
          error: "Model returned no parsed output.",
          meta: {
            upstreamCalls: [
              {
                url: upstreamUrl,
                status: 200,
                latencyMs,
                ok: false,
                error: "no parsed_output",
              },
            ],
          },
        },
        { status: 502 },
      );
    }

    console.log(
      `[briefing] model=${MODEL} latency=${latencyMs}ms ` +
        `input=${response.usage.input_tokens} ` +
        `output=${response.usage.output_tokens} ` +
        `cache_read=${response.usage.cache_read_input_tokens ?? 0} ` +
        `cache_write=${response.usage.cache_creation_input_tokens ?? 0}`,
    );

    return NextResponse.json({
      briefing,
      meta: {
        model: MODEL,
        latencyMs,
        usage: {
          inputTokens: response.usage.input_tokens,
          outputTokens: response.usage.output_tokens,
          cacheReadTokens: response.usage.cache_read_input_tokens ?? 0,
          cacheCreationTokens: response.usage.cache_creation_input_tokens ?? 0,
        },
        upstreamCalls: [
          {
            url: upstreamUrl,
            status: 200,
            latencyMs,
            ok: true,
          },
        ],
      },
    });
  } catch (error) {
    if (error instanceof Anthropic.AuthenticationError) {
      return NextResponse.json(
        { error: "Anthropic authentication failed. Check ANTHROPIC_API_KEY." },
        { status: 401 },
      );
    }
    if (error instanceof Anthropic.RateLimitError) {
      return NextResponse.json(
        { error: "Anthropic rate limit hit. Retry shortly." },
        { status: 429 },
      );
    }
    if (error instanceof Anthropic.APIError) {
      return NextResponse.json(
        { error: `Anthropic API error (${error.status}): ${error.message}` },
        { status: 502 },
      );
    }
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { error: `Briefing generation failed: ${message}` },
      { status: 502 },
    );
  }
}

function round(value: number, decimals: number): number {
  const factor = 10 ** decimals;
  return Math.round(value * factor) / factor;
}
